# Generated by Django 5.2.6 on 2025-10-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
